# 自动构建文件
language: node_js
node_js:
  - "10"
cache: npm

branches:
  only:
    - master

script:
  - npm run build && echo "gitmall.yw1551.cn" > ./dist/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  verbose: true
  local_dir: ./dist/
  on:
    branch: master
