# 自动构建文件
language: node_js
node_js:
  - "10"
cache: npm

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  verbose: true
  on:
    branch: master
